# Generated by Django 5.1.6 on 2025-03-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectapplicationmodel',
            name='is_selected',
        ),
    ]
