# Generated by Django 5.1.6 on 2025-03-09 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_teammodel_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcyclemodel',
            name='application_end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 17, 27, 42, 676748, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcyclemodel',
            name='application_start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 17, 28, 9, 64505, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
