# Generated by Django 5.1.6 on 2025-03-03 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='semester',
        ),
        migrations.AddField(
            model_name='customuser',
            name='passout_year',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2025)]),
        ),
    ]
