name: Auto-Issue Numbering

on:
  issues:
    types: [opened]

jobs:
  add-number:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Issue Number
        id: issue
        run: echo "number=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Use Issue Number
        run: |
          echo "New issue created: #${{ env.number }}"
          # Example: You can automate actions here using the issue number,
          # such as adding comments, labels, or creating branches.
